name: ghost_pixel
description: Your data remains secure as it is seamlessly embedded into the image. Even when viewing the image, no one will suspect that it contains hidden information.
version: 1.1.1
repository: https://github.com/Anykeykin/ghost_pixel

environment:
  sdk: ^3.1.5

dependencies:
  image: ^4.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

keywords:
  - steganography
  - image-processing
  - data-hiding
  - encryption
  - compression
  - flutter
  - dart
  - security
  - byte-manipulation
  - png
  - file-hiding
  - image-encryption
  - data-security
  - lossless-compression
  - flutter-plugin
  - cross-platform
  - privacy
  - cryptography
  - byte-array
  - image-steganography