name: ghost_pixel
description: Your data remains secure as it is seamlessly embedded into the image. Even when viewing the image, no one will suspect that it contains hidden information.
version: 1.0.0

environment:
  sdk: ^3.1.5

dependencies:
  image: ^3.2.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
